const LG_ROW_CARD_COUNT = 4;
const MD_ROW_CARD_COUNT = 2;
const SM_ROW_CARD_COUNT = 1;

const LG_INITIAL_CARD_COUNT = 12;
const MD_INITIAL_CARD_COUNT = 6;
const SM_INITIAL_CARD_COUNT = 5;

export default {
    LG_ROW_CARD_COUNT,
    MD_ROW_CARD_COUNT,
    SM_ROW_CARD_COUNT,
    LG_INITIAL_CARD_COUNT,
    MD_INITIAL_CARD_COUNT,
    SM_INITIAL_CARD_COUNT
}